dist: xenial
language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -r CryptoBook-py/requirements/dev.txt
    - pip install pytest-cov
    - pip install coveralls
script:
    - pytest --cov=CryptoBook-py/
after_success:
    - coveralls
